#first hello CI CD
name: Hello
  on:
    push: 
      branch: [main]

jobs:
  greet:
  runs-on: ubuntu-latest
  steps:
    -name: say hello to user
      run: echo "hello dosto"

    -name: say hello to username
      run: echo "hello $USER"
